name = tnt_extras
title = TNT Extras
description = Makes TNT blasts effect different types of blocks differently.
depends = default, vessels
optional_depends = nyancat, xdecor
min_minetest_version = 0.4.10